id: P002926
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:28:50.992847
source_metadata:
  id: bdr:W1CZ1011
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོ
  author: ''
  volumes:
    5ef0271ac6c9434e83ee2cbc67287abf:
      image_group_id: I1CZ1020
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
